//! Golden tests for animated sprite — Tier-2 correctness gate.
//!
//! Cases (a)–(d) are hand-derived from the committed fixture
//! `crates/render/tests/fixtures/anim.gif` (generated by `gen_fixture.rs`).
//!
//! Fixture spec (see gen_fixture.rs):
//!   32×32 RGBA8, 4 frames, transparent background (0,0,0,0),
//!   disk radius 6, disk center y = 16.
//!   f0: cx=8,  color (220,70,70,255)   red
//!   f1: cx=14, color (70,200,70,255)   green
//!   f2: cx=20, color (70,70,220,255)   blue
//!   f3: cx=26, color (220,200,70,255)  yellow
//!
//! All oracles are independent of implementation internals:
//!   selection = floor(elapsed_nanos / frame_dur_nanos) % frame_count
//!   convert area Rect(0,0,16,8) → identity resize (cols*2=32, rows*4=32 = src 32×32)

use render::{convert, AnimatedSprite, Cell};
use ratatui::layout::Rect;
use scene_core::color::Rgba;
use std::time::Duration;

// ── shared setup ─────────────────────────────────────────────────────────────

fn load_sprite() -> AnimatedSprite {
    let fixture_bytes = std::fs::read(
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/anim.gif"),
    )
    .expect("anim.gif fixture must exist (run b2-t1 / gen_fixture first)");
    AnimatedSprite::from_gif(&fixture_bytes, Duration::from_millis(100))
        .expect("anim.gif must decode without error")
}

// ── Case (a): frame-index selection on the from_gif sprite ───────────────────

/// All five instants are pure arithmetic on the 4-frame / 100 ms sprite.
///
/// Formula: index = floor(elapsed_nanos / 100_000_000) % 4
///
///   t = 0 ms         → floor(0)      = 0,  0 % 4 = 0
///   t = 99 ms 999999 → floor(0.999…) = 0,  0 % 4 = 0  (1 ns before boundary)
///   t = 100 ms       → floor(1.0)    = 1,  1 % 4 = 1  (boundary flip)
///   t = 400 ms       → floor(4.0)    = 4,  4 % 4 = 0  (full-cycle wrap)
///   t = 550 ms       → floor(5.5)    = 5,  5 % 4 = 1
///
/// These run through the full decode path (not a synthetic sprite), so they
/// corroborate b1-t1 unit tests while also exercising from_gif.
#[test]
fn golden_case_a_frame_index_selection() {
    let sprite = load_sprite();
    let dur = Duration::from_millis(100);

    assert_eq!(
        sprite.frame_index_at(Duration::ZERO),
        0,
        "t=0 must be frame 0"
    );
    assert_eq!(
        sprite.frame_index_at(dur - Duration::from_nanos(1)),
        0,
        "t=100ms-1ns must still be frame 0 (last nanosecond of first window)"
    );
    assert_eq!(
        sprite.frame_index_at(dur),
        1,
        "t=100ms (exact boundary) must flip to frame 1"
    );
    assert_eq!(
        sprite.frame_index_at(Duration::from_millis(400)),
        0,
        "t=400ms (4 × 100ms full cycle) must wrap to frame 0"
    );
    assert_eq!(
        sprite.frame_index_at(Duration::from_millis(550)),
        1,
        "t=550ms: floor(550/100)=5, 5%4=1"
    );
}

// ── Case (b): frame count from the committed fixture ─────────────────────────

/// The committed anim.gif was generated with 4 frames.
/// This corroborates from_gif on the real on-disk asset, mirroring how
/// golden.rs pins sprite.png rather than an inline image.
#[test]
fn golden_case_b_frame_count_from_fixture() {
    let sprite = load_sprite();
    assert_eq!(sprite.frame_count(), 4, "anim.gif must decode to 4 frames");
}

// ── Case (c): distinct source frames → distinct Grids ────────────────────────

/// Converting frame 0 and frame 2 through `convert` must yield different
/// `Grid`s. This proves animation actually changes pixels — not a
/// static frozen-frame-0 bug.
///
/// Area Rect(0,0,16,8) → identity resize (32×32 src, cols*2=32, rows*4=32).
///
///   frame 0: red disk  at cx=8.  Cell (4,4) covers src x∈{8,9}, y∈{16..19}.
///            dx=0..1, dy=0..3 from cx=8, cy=16 → all inside r=6 → Glyph.
///   frame 2: blue disk at cx=20. Same cell: |8-20|=12 > r=6 → Transparent.
///
/// Grid::PartialEq compares every cell — the two grids differ at (4,4).
#[test]
fn golden_case_c_distinct_frames_produce_distinct_grids() {
    let sprite = load_sprite();
    let area = Rect::new(0, 0, 16, 8);

    // frame_index_at(0ms)   = 0 → frame 0 (red, cx=8)
    // frame_index_at(200ms) = floor(2.0) % 4 = 2 → frame 2 (blue, cx=20)
    let g0 = convert(sprite.frame_at(Duration::ZERO), area);
    let g2 = convert(sprite.frame_at(Duration::from_millis(200)), area);

    assert_ne!(
        g0,
        g2,
        "frame 0 (red disk cx=8) and frame 2 (blue disk cx=20) \
         must produce different Grids — animation is real"
    );
}

// ── Case (d): hand-derived pixel values at the identity-resize area ───────────

/// Area Rect(0,0,16,8):
///   aspect = 32/32 = 1.0
///   cols   = 16
///   rows   = round(16 / (2 × 1.0)) = round(8.0) = 8
///   resize_exact(32, 32) → identity (no Lanczos bleed).
///
/// Cell (tx=4, ty=4) → px = 8, py = 16.
///   Dot positions (via DOTS table): (8,16),(8,17),(8,18),(9,16),(9,17),(9,18),(8,19),(9,19)
///   Frame 0 disk: cx=8, cy=16, r=6.
///     (8-8)²+(16-16)² = 0 ≤ 36 → inside red  ← all 8 dots similarly inside
///   All 8 dots opaque red (220,70,70): same luma → all ≥ avg → mask=0xFF → U+28FF.
///   fg = mean of 8 identical pixels = Rgba::rgb(220,70,70).
///
/// Cell (tx=0, ty=0) → px = 0, py = 0.
///   Nearest disk pixel (cx=8, cy=16) at distance sqrt(64+256) ≈ 17.9 >> r=6.
///   All 8 dot positions outside the disk → transparent background → Cell::Transparent.
#[test]
fn golden_case_d_hand_derived_region_frame0() {
    let sprite = load_sprite();
    let area = Rect::new(0, 0, 16, 8);
    let grid = convert(sprite.frame_at(Duration::ZERO), area);

    assert_eq!(grid.cols(), 16, "case (d): expected 16 cols");
    assert_eq!(grid.rows(), 8, "case (d): expected 8 rows");

    assert_eq!(
        grid.get(4, 4),
        Cell::Glyph {
            ch: '\u{28FF}', // ⣿ — all 8 dots lit, mask = 0xFF
            color: Rgba::rgb(220, 70, 70),
        },
        "case (d): cell (4,4) covers src x∈{{8,9}}, y∈{{16..19}} — \
         all inside red disk (cx=8, r=6) → fully-lit glyph in disk color"
    );

    assert_eq!(
        grid.get(0, 0),
        Cell::Transparent,
        "case (d): cell (0,0) covers src x∈{{0,1}}, y∈{{0..3}} — \
         all outside disk (cx=8, r=6, dist≈18) → Transparent"
    );
}
