//! Bundled first-party raster assets for the braille UI chrome (spec
//! `22-braille-ui-chrome.md`). Every asset here is project-owned art
//! (generated by a checked-in `examples/gen_*.rs` generator, which IS the
//! provenance/license) — no third-party sourcing.

/// Rounded-rect panel background, 64×32 RGBA8. Corners are alpha-transparent
/// (hard edge, radius 8); the fill is opaque white so downstream multiply-tint
/// (`dots::tint`) passes the Idle/Hover/Press colors through unchanged.
///
/// Generated by `examples/gen_button_panel.rs`.
pub const BUTTON_PANEL: &[u8] = include_bytes!("assets/button_panel.png");

/// Home icon, 32×32 RGBA8. Flat opaque-white silhouette on an
/// alpha-transparent background (hard edge) — never a Unicode glyph
/// substitute (spec line 10: no `⌂`).
///
/// Generated by `examples/gen_button_icons.rs`.
pub const ICON_HOME: &[u8] = include_bytes!("assets/icon_home.png");

/// Left-arrow icon, 32×32 RGBA8. Flat opaque-white silhouette on an
/// alpha-transparent background (hard edge) — never a Unicode glyph
/// substitute (spec line 10: no `◀`).
///
/// Generated by `examples/gen_button_icons.rs`.
pub const ICON_ARROW_LEFT: &[u8] = include_bytes!("assets/icon_arrow_left.png");

/// Right-arrow icon, 32×32 RGBA8. Flat opaque-white silhouette on an
/// alpha-transparent background (hard edge) — never a Unicode glyph
/// substitute (spec line 10: no `▶`).
///
/// Generated by `examples/gen_button_icons.rs`.
pub const ICON_ARROW_RIGHT: &[u8] = include_bytes!("assets/icon_arrow_right.png");

/// Filled position-dot icon, 16×16 RGBA8. Opaque solid circle on an
/// alpha-transparent background (hard edge) — the "current page" indicator
/// in the roster carousel's dot row (spec `24-roster-carousel.md` line 10:
/// asset-based, never a Unicode bullet).
///
/// Generated by `examples/gen_position_dots.rs`.
pub const DOT_FILLED: &[u8] = include_bytes!("assets/dot_filled.png");

/// Unfilled position-dot icon, 16×16 RGBA8. Same solid-circle geometry as
/// `DOT_FILLED` but dimmer, on an alpha-transparent background (hard edge) —
/// the "other page" indicator in the roster carousel's dot row.
///
/// Generated by `examples/gen_position_dots.rs`.
pub const DOT_UNFILLED: &[u8] = include_bytes!("assets/dot_unfilled.png");

#[cfg(test)]
mod tests {
    use super::*;

    fn decode() -> image::RgbaImage {
        image::load_from_memory(BUTTON_PANEL)
            .expect("BUTTON_PANEL must decode as a valid image")
            .to_rgba8()
    }

    /// The bundled bytes decode without error and are the pinned 64×32
    /// dimensions the b3 render pipeline is fitted to.
    #[test]
    fn button_panel_decodes() {
        let img = decode();
        assert_eq!(img.dimensions(), (64, 32), "panel must be 64x32");
    }

    /// Corners must be alpha-transparent — "rounded" comes from the alpha
    /// channel, not a drawn shape (spec line 9: no new rasterizer).
    #[test]
    fn button_panel_corners_transparent() {
        let img = decode();
        let (w, h) = img.dimensions();
        for (x, y) in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)] {
            let alpha = img.get_pixel(x, y)[3];
            assert!(
                alpha < 128,
                "corner ({x},{y}) must be alpha-transparent, got alpha={alpha}"
            );
        }
    }

    /// Center pixel must be fully opaque — the panel actually has a solid
    /// body, not just an all-transparent image.
    #[test]
    fn button_panel_center_opaque() {
        let img = decode();
        let (w, h) = img.dimensions();
        let alpha = img.get_pixel(w / 2, h / 2)[3];
        assert!(
            alpha >= 250,
            "center pixel must be opaque, got alpha={alpha}"
        );
    }
}

#[cfg(test)]
mod icon_tests {
    use super::*;

    const ICONS: [(&[u8], &str); 3] = [
        (ICON_HOME, "icon_home"),
        (ICON_ARROW_LEFT, "icon_arrow_left"),
        (ICON_ARROW_RIGHT, "icon_arrow_right"),
    ];

    fn decode(bytes: &[u8], name: &str) -> image::RgbaImage {
        image::load_from_memory(bytes)
            .unwrap_or_else(|e| panic!("{name} must decode as a valid image: {e}"))
            .to_rgba8()
    }

    /// Every bundled icon decodes without error and is the pinned 32×32
    /// dimensions the b3 render pipeline is fitted to.
    #[test]
    fn icons_decode() {
        for (bytes, name) in ICONS {
            let img = decode(bytes, name);
            assert_eq!(img.dimensions(), (32, 32), "{name} must be 32x32");
        }
    }

    /// Background must be alpha-transparent at all four corners — the
    /// silhouette sits on an alpha ground, not a solid rect (spec line 9-10:
    /// no new rasterizer, no Unicode glyph substitute).
    #[test]
    fn icons_background_transparent() {
        for (bytes, name) in ICONS {
            let img = decode(bytes, name);
            let (w, h) = img.dimensions();
            for (x, y) in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)] {
                let alpha = img.get_pixel(x, y)[3];
                assert!(
                    alpha < 128,
                    "{name} corner ({x},{y}) must be alpha-transparent, got alpha={alpha}"
                );
            }
        }
    }

    /// Center pixel must be a fully opaque silhouette body — proves a real
    /// shape exists, not an all-transparent image.
    #[test]
    fn icons_silhouette_opaque() {
        for (bytes, name) in ICONS {
            let img = decode(bytes, name);
            let (w, h) = img.dimensions();
            let alpha = img.get_pixel(w / 2, h / 2)[3];
            assert!(
                alpha >= 250,
                "{name} center pixel must be opaque, got alpha={alpha}"
            );
        }
    }
}

#[cfg(test)]
mod dot_tests {
    use super::*;

    fn decode(bytes: &[u8], name: &str) -> image::RgbaImage {
        image::load_from_memory(bytes)
            .unwrap_or_else(|e| panic!("{name} must decode as a valid image: {e}"))
            .to_rgba8()
    }

    /// Both dot assets decode without error and are the pinned 16×16
    /// dimensions the b3 render pipeline is fitted to.
    #[test]
    fn dots_decode() {
        for (bytes, name) in [(DOT_FILLED, "dot_filled"), (DOT_UNFILLED, "dot_unfilled")] {
            let img = decode(bytes, name);
            assert_eq!(img.dimensions(), (16, 16), "{name} must be 16x16");
        }
    }

    /// Corners must be alpha-transparent — the dot is a circle on an alpha
    /// ground, not a solid square (spec line 10: no Unicode bullets, and no
    /// new rasterizer means the transparency must come from the asset).
    #[test]
    fn dots_background_transparent() {
        for (bytes, name) in [(DOT_FILLED, "dot_filled"), (DOT_UNFILLED, "dot_unfilled")] {
            let img = decode(bytes, name);
            let (w, h) = img.dimensions();
            for (x, y) in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)] {
                let alpha = img.get_pixel(x, y)[3];
                assert!(
                    alpha < 128,
                    "{name} corner ({x},{y}) must be alpha-transparent, got alpha={alpha}"
                );
            }
        }
    }

    /// Center pixel must be fully opaque on both assets — proves a real
    /// solid circle (not a hollow ring), which the b3-t2/b3-t3 render
    /// pipeline's center-sampling depends on.
    #[test]
    fn dots_center_opaque() {
        for (bytes, name) in [(DOT_FILLED, "dot_filled"), (DOT_UNFILLED, "dot_unfilled")] {
            let img = decode(bytes, name);
            let (w, h) = img.dimensions();
            let alpha = img.get_pixel(w / 2, h / 2)[3];
            assert!(
                alpha >= 250,
                "{name} center pixel must be opaque, got alpha={alpha}"
            );
        }
    }

    /// Filled and unfilled must be genuinely distinct assets — both at the
    /// raw byte level and in decoded center-pixel color (filled brighter
    /// than unfilled) — proving two real rasters, not one file reused with
    /// a runtime tint standing in for the other.
    #[test]
    fn dots_are_distinct() {
        assert_ne!(
            DOT_FILLED, DOT_UNFILLED,
            "DOT_FILLED and DOT_UNFILLED must not be byte-identical"
        );

        let filled = decode(DOT_FILLED, "dot_filled");
        let unfilled = decode(DOT_UNFILLED, "dot_unfilled");
        let (w, h) = filled.dimensions();
        let filled_center = filled.get_pixel(w / 2, h / 2);
        let unfilled_center = unfilled.get_pixel(w / 2, h / 2);
        assert_ne!(
            filled_center, unfilled_center,
            "filled and unfilled center pixel color must differ"
        );
        let filled_brightness: u32 =
            filled_center[0] as u32 + filled_center[1] as u32 + filled_center[2] as u32;
        let unfilled_brightness: u32 =
            unfilled_center[0] as u32 + unfilled_center[1] as u32 + unfilled_center[2] as u32;
        assert!(
            filled_brightness > unfilled_brightness,
            "filled dot must be brighter than unfilled: filled={filled_brightness} unfilled={unfilled_brightness}"
        );
    }
}
