//! Bundled first-party raster assets for the braille UI chrome (spec
//! `22-braille-ui-chrome.md`). Chrome (panels/frames) is generated by a
//! checked-in `examples/gen_*.rs` generator (which IS the provenance); the
//! icon/dot glyphs are sourced from Google's Material Icons via the
//! `material-icons-png` mirror (github.com/material-icons/material-icons-png,
//! Apache License 2.0, white variant) — real icon art, not procedurally
//! generated. The title logo is procedurally rendered
//! (`scenes::title_logo`), not a bundled raster.

/// Rounded-rect panel background, 64×32 RGBA8. Corners are alpha-transparent
/// (hard edge, radius 8); the fill is opaque white so downstream multiply-tint
/// (`dots::tint`) passes the Idle/Hover/Press colors through unchanged.
///
/// Generated by `examples/gen_button_panel.rs`.
pub const BUTTON_PANEL: &[u8] = include_bytes!("assets/button_panel.png");

/// Hollow bordered-frame panel, 64×32 RGBA8. Opaque border ring; the interior
/// is alpha-transparent (contrast `BUTTON_PANEL`'s opaque body) — used as the
/// non-interactive title box frame and a text `Button`'s bordered background.
///
/// Generated by `examples/gen_frame_panel.rs`.
pub const FRAME_PANEL: &[u8] = include_bytes!("assets/frame_panel.png");

/// Home icon, 48×48 RGBA8. White glyph on an alpha-transparent background —
/// never a Unicode glyph substitute (spec line 10: no `⌂`).
///
/// Source: material-icons-png `png/white/home/baseline-2x.png` (Apache 2.0).
pub const ICON_HOME: &[u8] = include_bytes!("assets/icon_home.png");

/// Left-arrow icon, 48×48 RGBA8. A bold solid triangle (not a thin
/// line-art arrow glyph) on an alpha-transparent background — never a
/// Unicode glyph substitute (spec line 10: no `◀`). `arrow_back`'s thin
/// stroke-based glyph was tried first and reverted: at the ~12×12-dot size
/// these render at in-game, its directional detail was lost entirely, and
/// left/right became visually indistinguishable from each other.
///
/// Source: material-icons-png `png/white/play_arrow/baseline-2x.png`
/// (Apache 2.0), horizontally mirrored.
pub const ICON_ARROW_LEFT: &[u8] = include_bytes!("assets/icon_arrow_left.png");

/// Egg icon, 48×48 RGBA8. A bold solid egg silhouette on an alpha-transparent
/// background, for the roster's Hatchery-entry badge (a house-badge sibling).
/// Solid, not line-art, so it survives the ~12×12-dot badge size.
pub const ICON_EGG: &[u8] = include_bytes!("assets/icon_egg.png");

/// Right-arrow icon, 48×48 RGBA8. A bold solid triangle — see
/// `ICON_ARROW_LEFT`'s doc comment for why this replaced the thin
/// `arrow_forward` line-art glyph.
///
/// Source: material-icons-png `png/white/play_arrow/baseline-2x.png` (Apache 2.0).
pub const ICON_ARROW_RIGHT: &[u8] = include_bytes!("assets/icon_arrow_right.png");

/// Filled position-dot icon, 48×48 RGBA8. Opaque solid white circle on an
/// alpha-transparent background — the "current page" indicator in the
/// roster carousel's dot row (spec `24-roster-carousel.md` line 10:
/// asset-based, never a Unicode bullet).
///
/// Source: material-icons-png `png/white/fiber_manual_record/baseline-2x.png` (Apache 2.0).
pub const DOT_FILLED: &[u8] = include_bytes!("assets/dot_filled.png");

/// Unfilled position-dot icon, 48×48 RGBA8. Same solid-circle geometry as
/// `DOT_FILLED` (same source shape), dimmed to ~55% brightness — kept as a
/// same-shape/different-brightness pair rather than a ring outline because
/// a thin ring doesn't survive the extreme downsampling to the ~4×4-dot
/// size these render at in the roster carousel's dot row (verified: a ring
/// variant was tried and rendered as invisible at that size).
///
/// Derived from material-icons-png `png/white/fiber_manual_record/baseline-2x.png`
/// (Apache 2.0) — same source raster as `DOT_FILLED`, recolored.
pub const DOT_UNFILLED: &[u8] = include_bytes!("assets/dot_unfilled.png");

/// Spoils candy icon, 64×64 RGBA8. Alpha-transparent background — the
/// PostBattle spoils band's per-item icon (spec `46-post-battle-results-screen.md`).
pub const ICON_SPOIL_CANDY: &[u8] = include_bytes!("assets/icon_spoil_candy.png");

/// Undefined-egg sprite, 220×280 RGBA8: a dark egg body with a bold, chunky,
/// bright-yellow question mark. Rendered UNTINTED so the `?` stays yellow
/// after per-cell braille color averaging (its strokes are deliberately fat
/// for this). Bundled first-party asset.
pub const EGG_UNKNOWN: &[u8] = include_bytes!("assets/egg_unknown.png");

#[cfg(test)]
mod tests {
    use super::*;

    fn decode() -> image::RgbaImage {
        image::load_from_memory(BUTTON_PANEL)
            .expect("BUTTON_PANEL must decode as a valid image")
            .to_rgba8()
    }

    /// The bundled bytes decode without error and are the pinned 64×32
    /// dimensions the b3 render pipeline is fitted to.
    #[test]
    fn button_panel_decodes() {
        let img = decode();
        assert_eq!(img.dimensions(), (64, 32), "panel must be 64x32");
    }

    /// Corners must be alpha-transparent — "rounded" comes from the alpha
    /// channel, not a drawn shape (spec line 9: no new rasterizer).
    #[test]
    fn button_panel_corners_transparent() {
        let img = decode();
        let (w, h) = img.dimensions();
        for (x, y) in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)] {
            let alpha = img.get_pixel(x, y)[3];
            assert!(
                alpha < 128,
                "corner ({x},{y}) must be alpha-transparent, got alpha={alpha}"
            );
        }
    }

    /// Center pixel must be fully opaque — the panel actually has a solid
    /// body, not just an all-transparent image.
    #[test]
    fn button_panel_center_opaque() {
        let img = decode();
        let (w, h) = img.dimensions();
        let alpha = img.get_pixel(w / 2, h / 2)[3];
        assert!(
            alpha >= 250,
            "center pixel must be opaque, got alpha={alpha}"
        );
    }
}

#[cfg(test)]
mod frame_panel_tests {
    use super::*;

    fn decode() -> image::RgbaImage {
        image::load_from_memory(FRAME_PANEL)
            .expect("FRAME_PANEL must decode as a valid image")
            .to_rgba8()
    }

    /// The bundled bytes decode without error and are the pinned 64×32
    /// dimensions the b3 render pipeline is fitted to.
    #[test]
    fn frame_panel_decodes() {
        let img = decode();
        assert_eq!(img.dimensions(), (64, 32), "frame panel must be 64x32");
    }

    /// The border ring must be opaque along its straight edges (avoiding the
    /// rounded corners, which are alpha-transparent for any radius >= 1).
    #[test]
    fn frame_panel_border_opaque() {
        let img = decode();
        let (w, h) = img.dimensions();
        for (x, y) in [(0, h / 2), (w - 1, h / 2), (w / 2, 0), (w / 2, h - 1)] {
            let alpha = img.get_pixel(x, y)[3];
            assert!(
                alpha >= 250,
                "border midpoint ({x},{y}) must be opaque, got alpha={alpha}"
            );
        }
    }

    /// The interior must be alpha-transparent — this is the contract that
    /// distinguishes a hollow frame from `BUTTON_PANEL`'s solid opaque body.
    #[test]
    fn frame_panel_interior_transparent() {
        let img = decode();
        let (w, h) = img.dimensions();
        let alpha = img.get_pixel(w / 2, h / 2)[3];
        assert!(
            alpha < 128,
            "interior center pixel must be alpha-transparent, got alpha={alpha}"
        );
    }
}

#[cfg(test)]
mod spoil_candy_tests {
    use super::*;

    fn decode() -> image::RgbaImage {
        image::load_from_memory(ICON_SPOIL_CANDY)
            .expect("ICON_SPOIL_CANDY must decode as a valid image")
            .to_rgba8()
    }

    /// The bundled bytes decode without error and are the pinned 64×64
    /// dimensions the b4-t6 spoils band is fitted to.
    #[test]
    fn spoil_candy_decodes() {
        let img = decode();
        assert_eq!(img.dimensions(), (64, 64), "icon_spoil_candy must be 64x64");
    }

    /// Corners must be alpha-transparent — the icon sits on an alpha ground,
    /// not a solid rect.
    #[test]
    fn spoil_candy_corners_transparent() {
        let img = decode();
        let (w, h) = img.dimensions();
        for (x, y) in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)] {
            let alpha = img.get_pixel(x, y)[3];
            assert!(
                alpha < 128,
                "corner ({x},{y}) must be alpha-transparent, got alpha={alpha}"
            );
        }
    }

    /// Center pixel must be a fully opaque body — proves real content
    /// exists, not an all-transparent raster.
    #[test]
    fn spoil_candy_center_opaque() {
        let img = decode();
        let (w, h) = img.dimensions();
        let alpha = img.get_pixel(w / 2, h / 2)[3];
        assert!(
            alpha >= 250,
            "center pixel must be opaque, got alpha={alpha}"
        );
    }
}

#[cfg(test)]
mod icon_tests {
    use super::*;

    const ICONS: [(&[u8], &str); 4] = [
        (ICON_HOME, "icon_home"),
        (ICON_ARROW_LEFT, "icon_arrow_left"),
        (ICON_ARROW_RIGHT, "icon_arrow_right"),
        (ICON_EGG, "icon_egg"),
    ];

    fn decode(bytes: &[u8], name: &str) -> image::RgbaImage {
        image::load_from_memory(bytes)
            .unwrap_or_else(|e| panic!("{name} must decode as a valid image: {e}"))
            .to_rgba8()
    }

    /// Every bundled icon decodes without error and is the pinned 48×48
    /// dimensions the b3 render pipeline is fitted to.
    #[test]
    fn icons_decode() {
        for (bytes, name) in ICONS {
            let img = decode(bytes, name);
            assert_eq!(img.dimensions(), (48, 48), "{name} must be 48x48");
        }
    }

    /// Background must be alpha-transparent at all four corners — the
    /// silhouette sits on an alpha ground, not a solid rect (spec line 9-10:
    /// no new rasterizer, no Unicode glyph substitute).
    #[test]
    fn icons_background_transparent() {
        for (bytes, name) in ICONS {
            let img = decode(bytes, name);
            let (w, h) = img.dimensions();
            for (x, y) in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)] {
                let alpha = img.get_pixel(x, y)[3];
                assert!(
                    alpha < 128,
                    "{name} corner ({x},{y}) must be alpha-transparent, got alpha={alpha}"
                );
            }
        }
    }

    /// Center pixel must be a fully opaque silhouette body — proves a real
    /// shape exists, not an all-transparent image.
    #[test]
    fn icons_silhouette_opaque() {
        for (bytes, name) in ICONS {
            let img = decode(bytes, name);
            let (w, h) = img.dimensions();
            let alpha = img.get_pixel(w / 2, h / 2)[3];
            assert!(
                alpha >= 250,
                "{name} center pixel must be opaque, got alpha={alpha}"
            );
        }
    }
}

#[cfg(test)]
mod egg_unknown_tests {
    use super::*;

    /// The bundled bytes decode without error and are the pinned 220×280
    /// dimensions the egg tray render is fitted to.
    #[test]
    fn egg_unknown_decodes() {
        let img = image::load_from_memory(EGG_UNKNOWN)
            .expect("EGG_UNKNOWN must decode as a valid image")
            .to_rgba8();
        assert_eq!(img.dimensions(), (220, 280), "egg_unknown must be 220x280");
    }
}

#[cfg(test)]
mod dot_tests {
    use super::*;

    fn decode(bytes: &[u8], name: &str) -> image::RgbaImage {
        image::load_from_memory(bytes)
            .unwrap_or_else(|e| panic!("{name} must decode as a valid image: {e}"))
            .to_rgba8()
    }

    /// Both dot assets decode without error and are the pinned 48×48
    /// dimensions the b3 render pipeline is fitted to.
    #[test]
    fn dots_decode() {
        for (bytes, name) in [(DOT_FILLED, "dot_filled"), (DOT_UNFILLED, "dot_unfilled")] {
            let img = decode(bytes, name);
            assert_eq!(img.dimensions(), (48, 48), "{name} must be 48x48");
        }
    }

    /// Corners must be alpha-transparent — the dot is a circle on an alpha
    /// ground, not a solid square (spec line 10: no Unicode bullets, and no
    /// new rasterizer means the transparency must come from the asset).
    #[test]
    fn dots_background_transparent() {
        for (bytes, name) in [(DOT_FILLED, "dot_filled"), (DOT_UNFILLED, "dot_unfilled")] {
            let img = decode(bytes, name);
            let (w, h) = img.dimensions();
            for (x, y) in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)] {
                let alpha = img.get_pixel(x, y)[3];
                assert!(
                    alpha < 128,
                    "{name} corner ({x},{y}) must be alpha-transparent, got alpha={alpha}"
                );
            }
        }
    }

    /// `DOT_FILLED`'s center must be fully opaque — a real solid circle.
    #[test]
    fn dot_filled_center_opaque() {
        let img = decode(DOT_FILLED, "dot_filled");
        let (w, h) = img.dimensions();
        let alpha = img.get_pixel(w / 2, h / 2)[3];
        assert!(
            alpha >= 250,
            "dot_filled center pixel must be opaque, got alpha={alpha}"
        );
    }

    /// `DOT_UNFILLED` must also be a real solid circle (same shape as
    /// `DOT_FILLED` — see its doc comment for why a ring outline was tried
    /// and reverted: too thin to survive downsampling to the ~4×4-dot size
    /// these render at).
    #[test]
    fn dot_unfilled_center_opaque() {
        let img = decode(DOT_UNFILLED, "dot_unfilled");
        let (w, h) = img.dimensions();
        let alpha = img.get_pixel(w / 2, h / 2)[3];
        assert!(
            alpha >= 250,
            "dot_unfilled center pixel must be opaque, got alpha={alpha}"
        );
    }

    /// Filled and unfilled must be genuinely distinct assets — both at the
    /// raw byte level and in decoded center-pixel color (filled brighter
    /// than unfilled) — proving two real rasters, not one file reused with
    /// a runtime tint standing in for the other.
    #[test]
    fn dots_are_distinct() {
        assert_ne!(
            DOT_FILLED, DOT_UNFILLED,
            "DOT_FILLED and DOT_UNFILLED must not be byte-identical"
        );

        let filled = decode(DOT_FILLED, "dot_filled");
        let unfilled = decode(DOT_UNFILLED, "dot_unfilled");
        let (w, h) = filled.dimensions();
        let filled_center = filled.get_pixel(w / 2, h / 2);
        let unfilled_center = unfilled.get_pixel(w / 2, h / 2);
        assert_ne!(
            filled_center, unfilled_center,
            "filled and unfilled center pixel color must differ"
        );
        let filled_brightness: u32 =
            filled_center[0] as u32 + filled_center[1] as u32 + filled_center[2] as u32;
        let unfilled_brightness: u32 =
            unfilled_center[0] as u32 + unfilled_center[1] as u32 + unfilled_center[2] as u32;
        assert!(
            filled_brightness > unfilled_brightness,
            "filled dot must be brighter than unfilled: filled={filled_brightness} unfilled={unfilled_brightness}"
        );
    }
}
