[package]
name = "ascii_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ascii_test"
path = "src/main.rs"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
image = "0.25"

[[bin]]
name = "anim"
path = "src/anim.rs"

[[bin]]
name = "anim_bias"
path = "src/anim_bias.rs"

[[bin]]
name = "flow"
path = "src/flow.rs"

[[bin]]
name = "downrez"
path = "src/downrez.rs"

[[bin]]
name = "playframes"
path = "src/playframes.rs"

[[bin]]
name = "mkslash"
path = "src/mkslash.rs"

[[bin]]
name = "mkslash2"
path = "src/mkslash2.rs"

[[bin]]
name = "combat"
path = "src/combat.rs"


[[bin]]
name = "debug_holes_tmp"
path = "src/debug_holes_tmp.rs"

[[bin]]
name = "attach"
path = "src/attach.rs"
